Radioactive heating and fixed bottom boundary temperature
echoi/DynEarthSol pull request #1
Opened 2020-11-09 18:26 UTC by luh1202

2020-11-18 18:33 UTC, echoi requested changes
Thanks for submitting a useful new feature. Please address my comments so that I can merge it.

2020-11-18 18:33 UTC, echoi commented on fields.cxx
> +            double rh = (var.mat->hr(e))/(var.mat->cp(e)); //Radioactive heating
Shouldn't this term be integrated over volume as well?

2020-11-18 18:33 UTC, echoi commented on fields.cxx
> +
We can safely assume that temperature is fixed on the top surface but cannot assume the same for the bottom boundary. Please create an integer switch (cf. 'vbc_x0' etc) in parameters.hpp:struct BC, initialize it in input.cxx and modify the above code so that mantle_temperature is applied only when the switch has a certain value (e.g., >0).

2020-11-19 01:15 UTC, tan2 reviewed
It seems that the unit of hr is W/m^3. I would prefer to use W/kg so that when the effect of compressibility (ie. density can change with depth) in introduced in the future, the code of radiogenic heat generatation can remain unaffected.

Missing codes to read in mat.radiogenic_heating in input.cxx
 
All input parameters should be listed in examples/defaults.cfg

2020-11-19 01:15 UTC, tan2 commented on latest_input/rifting-2d.cfg
> +[sim]
Can you merge this file with examples/rifting-2d.cfg?

2020-11-19 22:31 UTC, luh1202 commented
Hello Dr. Tan, Dr. Choi,

Thanks for the suggestions, I’ll follow up with new commit accordingly.

Best regards,
Hao

From: Eh Tan <notifications@github.com>
Reply-To: echoi/DynEarthSol <reply@reply.github.com>
Date: Wednesday, November 18, 2020 at 19:16
To: echoi/DynEarthSol <DynEarthSol@noreply.github.com>
Cc: "Hao Lu (hlu1)" <hlu1@memphis.edu>, Author <author@noreply.github.com>
Subject: Re: [echoi/DynEarthSol] Radioactive heating and fixed bottom boundary temperature (#1)


@tan2 commented on this pull request.

It seems that the unit of hr is W/m^3. I would prefer to use W/kg so that when the effect of compressibility (ie. density can change with depth) in introduced in the future, the code of radiogenic heat generatation can remain unaffected.

Missing codes to read in mat.radiogenic_heating in input.cxx

All input parameters should be listed in examples/defaults.cfg

________________________________

In latest_input/rifting-2d.cfg<https://github.com/echoi/DynEarthSol/pull/1#discussion_r526524348>:

> @@ -0,0 +1,100 @@

+[sim]

Can you merge this file with examples/rifting-2d.cfg?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/echoi/DynEarthSol/pull/1#pullrequestreview-534003102>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AF6D5P3W2CEJWXEGYBZ2NB3SQRWUZANCNFSM4TPWPERA>.

2020-12-04 02:20 UTC, closed without merging